senzing-factory/dockerhub-util

- CHANGELOG.md
- Dockerfile
- README.md
- dockerhub-util.py
- requirements.txt
> Issue 3.dockter.1

- CHANGELOG.md
- Dockerfile
- dockerhub-util.py
> #3 Prepare for version

- dockerhub-util.py
> #3 Add docker images

- dockerhub-util.py
> #3 Update swagger-ui default

- dockerhub-util.py
> #3 Add non-senzing docker images

- README.md
- dockerhub-util.py
> Issue 3.dockter.5

- dockerhub-util.py
> #3 Update version

- dockerhub-util.py
> Issue 3.dockter.6

- dockerhub-util.py
> #12 added busybox

- README.md
- dockerhub-util.py
> #3 Add Bitnami information

- Dockerfile
- dockerhub-util.py
- requirements.txt
> #17 Improve determining most recent version

- CHANGELOG.md
- Dockerfile
- dockerhub-util.py
> #16 Prepare for versioning

- .gitignore
- dockerhub-util.py
> #20 Add environment variables for 'with-data'

- dockerhub-util.py
> #20 Add senzing-poc-server

- dockerhub-util.py
> #23 Fix versioning

- dockerhub-util.py
> #27 Added SENZING_DOCKER_IMAGE_VERSION_DATA_ENCRYPTION_AES256CBC_SAMPLE

- Dockerfile
> Remove requirementst.txt after pip install

- Dockerfile
> #35 Add python 3

- dockerhub-util.py
> Issue 35.dockter.2

- dockerhub-util.py
> #40 Add values for ELK stack

- dockerhub-util.py
> #40 Add bitnami/nginx

- dockerhub-util.py
> #40 Added SENZING_DOCKER_IMAGE_VERSION_BITNAMI_NGINX_INGRESS_CONTROLLER

- dockerhub-util.py
> #44 Added more exclusions

- dockerhub-util.py
> #44 Add SENZING_DOCKER_IMAGE_VERSION_BITNAMI_SHELL

- dockerhub-util.py
> #30 Update pinned versions

- dockerhub-util.py
> #30 Add SENZING_DOCKER_IMAGE_VERSION_DPAGE_PGADMIN4

- dockerhub-util.py
> #30 Update dpage/pgadmin version

- dockerhub-util.py
> #30 Update version

- .github/workflows/pylint.yaml
- .pylintrc
- CHANGELOG.md
- CONTRIBUTING.md
- Dockerfile
- README.md
- dockerhub-util.py
> Isssue 53.dockter.1

- CHANGELOG.md
- dockerhub-util.py
> #59 Add SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP_CONSOLE

- dockerhub-util.py
> #61 Update dpage/pgadmin

- .pylintrc
- dockerhub-util.py
> #61 Update hard-coded versions; remove unnecessary-dict-index-lookup

- dockerhub-util.py
> #61 Update hard-coded version

- .pylintrc
- dockerhub-util.py
> Issue 66.dockter.1

- dockerhub-util.py
> #77 Add docker images

- .github/CODEOWNERS
- .github/workflows/add-dependabot-request-to-project-t-comm.yaml
- .github/workflows/add-issue-to-project-t-comm.yaml
- .github/workflows/add-triage-label.yaml
- .github/workflows/build-docker-container.yaml
- .github/workflows/identify-customer.yaml
- .github/workflows/pylint.yaml
> #79 Modify workflows

- dockerhub-util.py
> #77 filter out staging

- dockerhub-util.py
> #61 Update hard-coded versions

- dockerhub-util.py
> #77 Add senzing/init-postgresql

- README.md
- dockerhub-util.py
> #68 Redact 'sha256-'

- CHANGELOG.md
- Dockerfile
- dockerhub-util.py
> #61 Prepare for versioned release

- dockerhub-util.py
> Issue 61.dockter.7

- .pylintrc
- CHANGELOG.md
- Dockerfile
- dockerhub-util.py
> #89 Migrate from V1 to V2 protocol

- dockerhub-util.py
> #89 Fix busybox version

- CHANGELOG.md
- Dockerfile
- dockerhub-util.py
> #92 Prepare for versioned release

- dockerhub-util.py
> Update pgadmin version

- CHANGELOG.md
- dockerhub-util.py
> #102 Update 'fixed' versions

- dockerhub-util.py
> #102 Update fixed versions

- Makefile
- dockerhub-util.py
> Issue 105.dockter.1

- dockerhub-util.py
> #105 Update pgadmin

- CHANGELOG.md
- Dockerfile
- dockerhub-util.py
> #109 Update versions

- README.md
- docs/development.md
- docs/examples.md
> Issue 113.dockter.1

- CHANGELOG.md
- Dockerfile
- dockerhub-util.py
> #102 Update non-senzing versions

- dockerhub-util.py
> #120 Add images

- CHANGELOG.md
- dockerhub-util.py
- docs/development.md
- docs/examples.md
> Update non-senzing versions

- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-factory-dependabot.yaml
- .github/workflows/add-to-project-factory.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
Issue number: senzing-factory/build-resources#179
> senzing-factory/build-resources#179 add slack notifications

- .github/dependabot.yml
- .github/renovate.json
> #160 use renovate for docker updates
